### ISSUE TITLE
Does not recognize proper load order

### ISSUE THREAD

**Issue by ebeneezersquid** [matortheeternal/smash#222]
Appears to be same as issue old #137, from what I can tell. Seeing it in both Fallout 4 and Skyrim SE. Using Mator Smash Version 1.0.2.0, xEdit Version 3.1.1

Getting Errors as it loads Patches to mods before the mods themselves, completely different orders than are loaded in Vortex or Wrye Bash.

**Comment by matortheeternal** [comment]
Not sure why you provided xEdit version, as that has no impact on this.

Please attach copies of all `*.txt` files from the game folder in `%LocalAppData%`.  Also please provide screenshots/logs showing how Smash is interpreting your load order.

Note that Creation Club ESLs are not currently supported and won't be loaded in the correct locations.

**Comment by syclonix** [comment]
I am having the exact same issue: 

Pluggins.txt from MO2: https://pastebin.com/raw/HZg1V3Vj
Mator Smash Load Order: https://imgur.com/a/Zz4DXz1
Mator Smash log: https://pastebin.com/raw/Qw358ZHz

Mator Smash was working beautifully until today. Now it reorders my plugins differently than how it is set in Mod Organizer 2. It is almost as if Mator Smash can no longer read the load order from MO2. FYI I am launching Mator Smash from inside MO2.

Prior to Mator Smash stopped working, I created a new profile in MO2. I don't know if this has anything to do with it, but when I switch back to my other profile the load order is also messed up in Mator Smash. Also, if it makes any difference I'm on Skyrim VR but configured Mator Smash to treat it like Skyrim SE.

I am using the latest version 1.02 and I tried the workaround solution of redating the plugins in Loot, but the button is greyed out.

**Comment by syclonix** [comment]
P.S. I deleted the multiple profiles in MO2. I also did a clean reinstall of MO2 and Mator Smash. I restored the "downloads" folder in MO2, reinstalled all my mods, ran LOOT, then ran Mator Smash. Unfortunately, Mator Smash still refuses to obey the MO2 load order. I don't know what else to try :/

**Comment by syclonix** [comment]
I fixed it thanks to [this reddit post](https://www.reddit.com/r/skyrimvr/comments/8poq1x/mator_smash_guide_for_skyrimvr_automated_conflict/)! The issue seems to be because Mator Smash doesn't directly support SkyrimVR so there's some manual tweaking that needs to be done everytime before running it:

> "Since there is no direct support how it handles plugins.txt folder is little different. Mator smash uses the plugins.txt folder inside your C:\Users(Username)\AppData\Local\Skyrim Special Edition folder (if you don't have this folder you must create one and make sure it's spelled exacly how i put it). So anytime you change your plugins and need to run mator smash you have to copy your updated plugins.txt to this folder. For Vortex users there will be a SkyrimVR folder right next to the special edition one so just copy the file over. For MO2 you will need to go to where you installed your MO2 mods and go to profiles folder then default(or profile name) and copy the plugins.txt from there."

**Comment by Barerock** [comment]
I'm not using SkyrimVR, just standard SE with MO2 v.2.4.2 and this is still an issue for me. Specifically it's loading MLU patches before MLU.esp and can't properly load it into the program as a consequence.

**Comment by CodeApex** [comment]
Heads up - this is 100% most likely because someone was reformatting, and then before they have launched the game again - they have been attempting to get all of their patches in order. In other words... The folder for where plugins.txt and everything are all supposed to go does NOT exist. Which is why it will not get the proper load order.

**Comment by SirenBrink** [comment]
Just wanted to pop in and say I ran into this issue while modding Skyrim VR.

The solution was to copy my (MO profile) plugins.txt over into "C:\Users\(Username)\AppData\Local\Skyrim Special Edition"

Yes, special edition, even though I'm on a VR profile. No clue why it suddenly stopped loading my profile's plugin.txt because I had run Skyrim VR before I even started adding mods.
