### ISSUE TITLE
Mator Smash lost ability to load plugins. 

### ISSUE THREAD

**Issue by Osais192** [matortheeternal/smash#235]
Can anyone give me some insight into an issue I'm having please?
In SSE my mator smash suddenly stopped being able to make and update patches. I already tried reinstalling the files. 

Some background info. 
Uses Vortex
instead of saying "smash.all" for everything, it now reads mostly "skip" and various messages like "Bash.combinded" and "bash.graphics" now appear. For months it has never used these tags before 
When i hit the green arrow the window closes but i can see a process in the task manager taking 0 cpu.
I can "make" a new patch but i can't "build" it. 
When i hit the patches tab "Smash Patch" is in bright red and all but 7 its plugins are too. In status it reads "Plugins not loaded". I'm assuming this is the issue, but so far I haven't been able to fix it. 
The log itself is showing no issues.

**Comment by matortheeternal** [comment]
The green arrow button should fix the "plugins not loaded" for you.  The program crashing suggests something else is broken, can't really guess what without knowing more information about your setup.

You can try loading fewer plugins into the program (e.g. just game and DLCs) to see if that fixes the issue.

**Comment by Osais192** [comment]
Well that revealed a few interesting things. In total I only have 126 plugins. 
Loading only the mods i already smash patched it still crashed (which is the strangest part)
DLC's, unofficial patch, and legacy of the dragon born, smashed correctly.

I'm going to smash mods one at a time and see if i can isolate a one causing it to fail. 
Will report back with findings.

**Comment by Osais192** [comment]
Solved it, by default Smasher is checking Smash Patch box during the load plugin phase when you first start the program, This is whats causing it to crash. 
Odd enough, how this problem never happened to me before, for months even. 

Manually deselecting and then selecting the "smash patch" checkbox greys out the "OK" button as I assume is intended. So that's good. 

On a side note i can also confirm "ELEX Hardcore" stalls the patcher significantly. I Know there was a thread open about that.  

And also thank you for such an awesome program.
